services:
  - type: web
    name: n8n
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    plan: starter
    envVars:
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "10000"
      - key: N8N_PROTOCOL
        value: "https"
